tasks:
  - init: |
      # Install Zig 0.12.0
      wget https://ziglang.org/download/0.12.0/zig-linux-x86_64-0.12.0.tar.xz
      tar -xf zig-linux-x86_64-0.12.0.tar.xz
      export PATH="$PATH:$PWD/zig-linux-x86_64-0.12.0"
